# Generated by Django 5.0.3 on 2024-03-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_contrib', models.CharField(max_length=20)),
                ('nome_logradoro_imovel', models.CharField(max_length=100)),
                ('num_imovel', models.IntegerField()),
                ('complemento_imovel', models.CharField(max_length=100)),
                ('bairro_imovel', models.CharField(max_length=100)),
                ('cep_imovel', models.CharField(max_length=15)),
                ('area_tereno', models.IntegerField()),
                ('metro_quad_terreno', models.IntegerField()),
            ],
        ),
    ]
