# Generated by Django 5.0.3 on 2024-03-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imoveis_sp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='bairro_imovel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='complemento_imovel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='nome_logradoro_imovel',
            field=models.CharField(max_length=255),
        ),
    ]
